(function(module) {
try {
  module = angular.module('templates-app');
} catch (e) {
  module = angular.module('templates-app', []);
}
module.run(['$templateCache', function($templateCache) {
  $templateCache.put('about/index.tpl.html',
    '<div>\n' +
    '  <h1>Angular in sails</h1>\n' +
    '\n' +
    '  <p>{{\'This page was\' + \'created by sails-generate-angular-gulp.\'}}</p>\n' +
    '</div>\n' +
    '');
}]);
})();

(function(module) {
try {
  module = angular.module('templates-app');
} catch (e) {
  module = angular.module('templates-app', []);
}
module.run(['$templateCache', function($templateCache) {
  $templateCache.put('header/index.tpl.html',
    '<div ng-controller="HeaderCtrl">\n' +
    '    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">\n' +
    '        <!-- Brand and toggle get grouped for better mobile display -->\n' +
    '        <div class="navbar-header">\n' +
    '            <button type="button" class="navbar-toggle" data-toggle="collapse"\n' +
    '                    data-target="#bs-example-navbar-collapse-1">\n' +
    '                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span\n' +
    '                    class="icon-bar"></span><span class="icon-bar"></span>\n' +
    '            </button>\n' +
    '            <a class="navbar-brand" href="/">Sails Angular </a>\n' +
    '            <!-- {{currentUser.role}}-->\n' +
    '        </div>\n' +
    '        <!-- Collect the nav links, forms, and other content for toggling -->\n' +
    '        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\n' +
    '            <ul class="nav navbar-nav">\n' +
    '                <li ng-repeat="navItem in navItems">\n' +
    '                    <a href="{{navItem.url}}"><i class="{{navItem.cssClass}}"></i>&nbsp; {{navItem.title}}</a>\n' +
    '                </li>\n' +
    '                <!-- only admin can view -->\n' +
    '                <!--<li ng-hide="currentUser.role!=4" ><a href="/users"><span class="fa fa-group fa-lg"></span>User List</a></li>-->\n' +
    '            </ul>\n' +
    '\n' +
    '\n' +
    '            <ul class="nav navbar-nav navbar-right">\n' +
    '                <li ><a href="/about"><span class="fa fa-question"></span> About</a></li>\n' +
    '                <li><a href="/login"><span class="fa fa-sign-in fa-lg"></span> Sign in</a></li>\n' +
    '                <li><a href="/register"><span class="fa fa-pencil fa-lg"></span> Register</a></li>\n' +
    '                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">\n' +
    '                    <span id="currentUserMenu" class="fa fa-user">User Name </span> <b class="caret"></b></a>\n' +
    '                    <ul class="dropdown-menu">\n' +
    '                        <li><a href="#"><span class="fa fa-user"></span> Profile</a></li>\n' +
    '                        <li><a href="#"><span class="fa fa-cogs"></span> Settings</a></li>\n' +
    '                        <li class="divider"></li>\n' +
    '                        <li><a href="/logout"><span class="fa fa-sign-out"></span> Logout</a></li>\n' +
    '                    </ul>\n' +
    '                </li>\n' +
    '            </ul>\n' +
    '        </div>\n' +
    '        <!-- /.navbar-collapse -->\n' +
    '    </nav>\n' +
    '</div>\n' +
    '');
}]);
})();

(function(module) {
try {
  module = angular.module('templates-app');
} catch (e) {
  module = angular.module('templates-app', []);
}
module.run(['$templateCache', function($templateCache) {
  $templateCache.put('home/index.tpl.html',
    '<div class="jumbotron">\n' +
    '    <h1>Generated by sails-generate-angular-gulp</h1>\n' +
    '\n' +
    '    <p class="lead">AngularJS + NodeJS + SailsJS = Awesome</p>\n' +
    '\n' +
    '    <p>Angular test Page\n' +
    '        <br><br>If you\'re seeing this page, then angular is working </p>\n' +
    '\n' +
    '    <div class="row">\n' +
    '        <div class="col-md-4  col-lg-4 col-lg-offset-2 pull-right">\n' +
    '            <p><a href="https://github.com/Karnith/sails-generate-angular-gulp" class="btn btn-success btn-lg"><i class="fa fa-github fa-2x"></i> View on Github</a></p>\n' +
    '        </div>\n' +
    '    </div>\n' +
    '\n' +
    '\n' +
    '</div>\n' +
    '<div class="col-lg-2">\n' +
    '    <h2>  <img src="../../images/logos/angularjs.png" alt="AngularJS" height="45"></h2>\n' +
    '    <p>AngularJS lets you extend HTML vocabulary for your application. The resulting environment is extraordinarily expressive, readable, and quick to develop.</p>\n' +
    '</div>\n' +
    '<div class="col-lg-3">\n' +
    '    <h2><img src="../../images/logos/nodejs.png" alt="Node.js" height="45"></h2>\n' +
    '    <p>Node.js is a platform built on Chrome\'s JavaScript runtime for easily building fast, scalable network applications.</p>\n' +
    '</div>\n' +
    '<div class="col-lg-2">\n' +
    '    <h2><img src="../../images/logos/sails-logo.png" alt="Sails.js" height="45"></h2>\n' +
    '    <p>Sails makes it easy to build custom, enterprise-grade Node.js apps. It is designed to emulate the familiar MVC pattern of frameworks like Ruby on Rails, but with support for the requirements of modern apps: data-driven APIs with a scalable, service-oriented architecture. </p>\n' +
    '\n' +
    '</div>\n' +
    '<div class="row">\n' +
    '    <div class="col-lg-12">\n' +
    '        <p class="text-align-center">Generated by <a href="https://github.com/Karnith/sails-generate-angular-gulp" target="_blank">sails-generate-angular-gulp</a></p>\n' +
    '    </div>\n' +
    '</div>');
}]);
})();

(function(module) {
try {
  module = angular.module('templates-app');
} catch (e) {
  module = angular.module('templates-app', []);
}
module.run(['$templateCache', function($templateCache) {
  $templateCache.put('users/index.tpl.html',
    '<h2>users\'s</h2>\n' +
    '\n' +
    '<div class="row">\n' +
    '    <div class="col-md-12">\n' +
    '        <p><strong>Sorting:</strong> {{tableParams.sorting()|json}}\n' +
    '        <table ng-table="tableParams" class="table">\n' +
    '            <tr ng-repeat="user in  $data">\n' +
    '                <td data-title="\'username\'" sortable="\'username\'">\n' +
    '                    <span ng-class="{ \'fa fa-info-circle\': user.title == \'666\',\'fa fa-dot-circle-o\': user.username != \'666\' }"> {{ user.username}}</span>\n' +
    '                </td>\n' +
    '                <td  data-title="\'email\'" sortable="\'email\'">\n' +
    '                    {{user.email }}\n' +
    '                </td>\n' +
    '                <td  data-title="\'first_name\'" sortable="\'first_name\'">\n' +
    '                    {{user.first_name }}\n' +
    '                </td>\n' +
    '                <td  data-title="\'role\'" sortable="\'role\'">\n' +
    '                    {{user.role }}\n' +
    '                </td>\n' +
    '            </tr>\n' +
    '        </table>\n' +
    '    </div>\n' +
    '</div>');
}]);
})();
